output:
  formats: colored-line-number
  sort-results: true

run:
  tests: true
  deadline: 2m
  skip-dirs:
  exclude-use-default: false
  allow-parallel-runners: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/alecthomas/chroma/quick
          - github.com/davecgh/go-spew/spew
          - github.com/fatih/color
  errcheck:
    check-type-assertions: true
  goconst:
    numbers: true
    min-occurances: 2
  gocritc:
    enabled-checks:
      - diagnostic
      - style
      - performance
    enabled-tags:
      - diagnostic
      - performance
      - experimental
      - style
  gocyclo:
    min-complexity: 200
  gofumpt:
    extra-rules: true
  golint:
    min-confidence: 0
  gosec:
    exclude-generated: false
  lll:
    line-length: 180
    tab-width: 2
  maligned:
    suggest-new: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  unused:
    go: "1.22"
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
      - name: add-constant
        disabled: true
      - name: unexported-return
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: banned-characters
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        arguments: [10]
      - name: unhandled-error
        disabled: true
      - name: var-naming
        disabled: true
      - name: function-length
        disabled: true
      - name: argument-limit
        disabled: true
      - name: file-header
        arguments:
          - "Copyright"

linters:
  enable-all: true

  disable:
    - exhaustruct
    - forbidigo
    - gochecknoglobals

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
